### ISSUE TITLE
unahndled exception utf-8

### ISSUE THREAD

**Issue by fredgrott** [WhisperArts/analyzer-formatter#15]
Unhandled exception:
FileSystemException: Failed to decode data using encoding 'utf-8', path = 'D:\fredgrttsstuff\GithubProjects\code_with_me\cookbook\bootsttrap_fulltest\reports\analyze_report.txt'
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      _File.readAsLinesSync (dart:io/file_impl.dart:590:36)
#3      parseAnalyzerReport (package:analyzer_formatter/src/analyzer_result_parser.dart:24:18)
#4      main (file:///D:/fluttersdk/myfluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer_formatter-0.2.0/bin/analyzer_formatter.dart:43:26)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
pub finished with exit code 255
PS D:\fredgrttsstuff\GithubProjects\code_with_me\cookbook\bootsttrap_fulltest>

**Comment by fartem** [comment]
@fredgrott hi. Can you describe your problem?

**Comment by fredgrott** [comment]
I fails on the standard output of analyzer, for example:

`Analyzing devops_lint_metrics...                                

   info - Prefer declaring const constructors on `@immutable` classes - lib\presentation\features\app\create_screen_for.dart:16:3 - prefer_const_constructors_in_immutables
   info - Avoid defining unused parameters in constructors - lib\presentation\features\app\create_screen_for.dart:17:5 - avoid_unused_constructor_parameters
   info - Avoid defining unused parameters in constructors - lib\presentation\features\app\create_screen_for.dart:18:5 - avoid_unused_constructor_parameters
   info - Use `ColoredBox` - lib\presentation\features\color\color_palettes_screen.dart:349:12 - use_colored_box
   info - Prefer declaring const constructors on `@immutable` classes - lib\presentation\features\color\scheme_label.dart:10:3 - prefer_const_constructors_in_immutables
   info - Avoid defining unused parameters in constructors - lib\presentation\features\color\scheme_label.dart:10:16 - avoid_unused_constructor_parameters
   info - Prefer declaring const constructors on `@immutable` classes - lib\presentation\features\color\scheme_view.dart:11:3 - prefer_const_constructors_in_immutables
   info - Avoid defining unused parameters in constructors - lib\presentation\features\color\scheme_view.dart:11:15 - avoid_unused_constructor_parameters
   info - Avoid positional boolean parameters - lib\presentation\features\components\component_screen.dart:92:3 - avoid_positional_boolean_parameters
   info - Prefer final for variable declarations if they are not reassigned - lib\presentation\features\elevation\elevation_screen.dart:23:5 - prefer_final_locals
   info - Prefer final for variable declarations if they are not reassigned - lib\presentation\features\elevation\elevation_screen.dart:24:5 - prefer_final_locals
   info - Sort pub dependencies alphabetically - pubspec.yaml:41:3 - sort_pub_dependencies
   info - Sort pub dependencies alphabetically - pubspec.yaml:47:3 - sort_pub_dependencies

`

Wil cause your tool to fail.

tool error output indicates that logic to decode utl-8 path is faulty

**Comment by fredgrott** [comment]
note did you assume format of utf-8 paths with platforms in mind?

**Comment by fartem** [comment]
@fredgrott. what OS do you use?
